version: "3.7"

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432
      
  quizzle-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    links:
      - db
      - redis 
    depends_on:
      - db
      - redis
    
    
  redis:
    image: redis
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command:  watchmedo auto-restart -- celery -A backend worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - quizzle-backend
    links:
      - db
      - redis

  flower:
        image: mher/flower
        environment: 
            - CELERY_BROKER_URL=redis://redis:6379/0
            - FLOWER_PORT=5555
        ports: 
            - 5555:5555
        depends_on: 
            - redis