version: "3.7"

services:
  db:
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
      
  quizzle-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    links:
      - db
      - redis 
    depends_on:
      - db
      - redis
    
    
  redis:
    image: redis
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command:  celery -A backend worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - quizzle-backend
    links:
      - db
      - redis

  # flower:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5555:5555'
  #   command: "celery -A myproject flower --address=0.0.0.0"
  #   depends_on:
  #     - celery
  #   links:
  #     - redis
  #     - celery