# Generated by Django 4.1 on 2022-08-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usereligibilitytest",
            old_name="test_score",
            new_name="test_type",
        ),
        migrations.AlterField(
            model_name="question",
            name="acceptance_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="usage_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usereligibilitytest",
            name="max_score",
            field=models.IntegerField(default=100),
        ),
    ]
