# Generated by Django 4.1 on 2022-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_appuser_password"),
        ("question", "0003_alter_question_c_alter_question_d"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="reviewer",
        ),
        migrations.AddField(
            model_name="question",
            name="reviewer",
            field=models.ManyToManyField(related_name="reviewer", to="user.appuser"),
        ),
    ]
