# Generated by Django 4.1 on 2022-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0005_rename_reviewer_question_reviewers_question_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT REVIEWED", "NOT REVIEWED"),
                    ("UNDER REVIEW", "UNDER REVIEW"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                ],
                default="NOT REVIEWED",
                max_length=256,
            ),
        ),
    ]
