# Generated by Django 4.1 on 2022-08-19 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_appuser_first_name_appuser_last_name"),
        ("question", "0008_remove_question_topic_question_topics"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEligibilityTestTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField()),
                ("has_ended", models.BooleanField(default=False)),
                (
                    "test_type",
                    models.CharField(
                        choices=[("SETTER", "SETTER"), ("REVIEWER", "REVIEWER")],
                        default="SETTER",
                        max_length=20,
                    ),
                ),
                (
                    "appuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.appuser"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="question.topic"
                    ),
                ),
            ],
        ),
    ]
