# Generated by Django 4.1 on 2022-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0009_usereligibilitytesttracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usereligibilitytesttracker",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
