# Generated by Django 4.1 on 2022-08-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0010_alter_usereligibilitytesttracker_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="usereligibilitytesttracker",
            name="duration",
            field=models.IntegerField(default=1),
        ),
    ]
