# Generated by Django 4.1 on 2022-08-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0012_question_explanation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="csv")),
            ],
        ),
    ]
