# Generated by Django 4.1 on 2022-08-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0013_csvfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GetQuestionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
