# Generated by Django 4.1 on 2022-08-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0014_question_reviewer_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="lang",
            field=models.CharField(default="en", max_length=3),
        ),
    ]
