# Generated by Django 4.1 on 2022-08-17 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=256)),
                ("points", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
            },
        ),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("is_setter", models.BooleanField()),
                ("is_reviewer", models.BooleanField()),
                ("questions_submitted", models.IntegerField(default=0)),
                ("questions_accepted", models.IntegerField(default=0)),
                ("questions_reviewed", models.IntegerField(default=0)),
                ("questions_rejected", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "reward",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.reward",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AppUser",
                "verbose_name_plural": "AppUsers",
            },
        ),
    ]
