# Generated by Django 4.1 on 2022-08-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="is_reviewer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="is_setter",
            field=models.BooleanField(default=False),
        ),
    ]
