# Generated by Django 4.1 on 2022-08-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_appuser_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
