# Generated by Django 4.1 on 2022-08-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_appuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
